### ISSUE TITLE
Correctly handle file output (avoid root -> /tmp)

### ISSUE THREAD

**Issue by rigred** [rigred/sandsifter#5]
https://github.com/rigred/sandsifter/issues/3#issuecomment-419006684

**Comment by rigred** [comment]
https://github.com/rigred/sandsifter/pull/6

Partial initially fix

**Comment by szlin** [comment]
I thought this issue could be closed by commit 63c4535

**Comment by rigred** [comment]
Yes. Just haven't closed yet.
